[global]
log_level = 'info'

[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[rest]
enabled = true
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'cudos-1'
rpc_addr = 'http://mainnet-full-node-02.hosts.cudos.org:26657'
grpc_addr = 'http://mainnet-full-node-02.hosts.cudos.org:9090'
websocket_addr = 'ws://mainnet-full-node-02.hosts.cudos.org:26657/websocket'
rpc_timeout = '20s'
account_prefix = 'cudos'
key_name = 'cudos-1_key'
store_prefix = 'ibc'
default_gas = 150000
max_gas = 10000000
gas_price = { price = 5000000000000, denom = 'acudos' }
gas_multiplier = 1.1
max_msg_num = 10
max_tx_size = 2097152
clock_drift = '10s'
max_block_time = '30s'
trusting_period = '14d'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
memo_prefix = 'Relayed by Cudo Ventures Hermes Relayer 2'

[[chains]]
id = 'osmosis-1'
rpc_addr = 'http://localhost:26657'
grpc_addr = 'http://localhost:9090'
websocket_addr = 'ws://localhost:26657/websocket'
rpc_timeout = '20s'
account_prefix = 'osmo'
key_name = 'osmosis-1_key'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 5000000
max_gas = 15000000
gas_price = { price = 0.0026, denom = 'uosmo' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '9d'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Cudo Ventures Hermes Relayer 2'
